name: 'airbyte_stripe'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
#profile: 'default'
profile: ''
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_stripe:
    materialized: table
    tmp:
      materialized: view

# TODO: add support for table prefix (_airbyte_stripe_customers_hashid AS _airbyte_customers_hashid,)
vars:
  airbyte_stripe:
    customers: "stripe_customers"
    customers_address: "stripe_customers_address"
    balance_transactions: "{{ source('airbyte_stripe','balance_transactions') }}" 
    charges_card: "stripe_charges_card"
    charges: "stripe_charges"
    payment_intents: "stripe_payment_intents"
    payouts: "stripe_payouts"
    refunds: "stripe_refunds"
    invoice_line_items: "stripe_invoice_line_items"
    invoice_line_items_period: "stripe_invoice_line_items_period"
    invoice_line_items_plan: "stripe_invoice_line_items_plan"
    invoices: "stripe_invoices"
    subscriptions: "stripe_subscriptions"
    plans: "stripe_plans"

  "dbt_date:time_zone": "UTC"
